version: "3"

volumes:
  mongodb_data:
    external: false

networks:
  cocoannotator:
    external: false

services:
  webserver:
    build:
      context: .
      dockerfile: ./backend/webserver/Dockerfile
    container_name: annotator_webclient
    image: tantael/multi-annotator:webserver-react
    restart: always
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=RandomSecretKeyHere
      - FILE_WATCHER=true
      - NAME=Test Annotator
    volumes:
      - "./datasets:/datasets"
      - "./models:/models"
      #- "/tmp/html:/usr/share/nginx/html"
    depends_on:
      - database
      - workers
    networks:
      - cocoannotator
  workers:
    container_name: annotator_workers
    image: tantael/multi-annotator:workers-react
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - "./backend/config:/workspace/config"
      - "./backend/webserver:/workspace/webserver"
      - "./backend/workers:/workspace/workers"
      - "./backend/database:/workspace/database"
      - "./datasets:/datasets"
    depends_on:
      - messageq
      - database
    ports:
      - 5555:5555
    networks:
      - cocoannotator
  messageq:
    image: rabbitmq:3
    container_name: annotator_message_q
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
    networks:
      - cocoannotator
  database:
    image: mongo:4.0
    container_name: annotator_mongodb
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "mongodb_data:/data/db"
    ports:
      - "27017:27017"
    command: "mongod --smallfiles --logpath=/dev/null"
    networks:
      - cocoannotator
  frontend:
    hostname: frontend
    image: tantael/multi-annotator:frontend-react

    container_name: multi_annotator_client
    build:
     context: .
     dockerfile: ./client/Dockerfile
    ports:
     - 3000:80
    volumes:
     - "./client:/workspace/client"
     #- "/tmp/html:/usr/share/nginx/html"

    networks:
     - cocoannotator
    depends_on:
     - webserver